-- SQL Customer Segmentation Analysis Project
-- Dataset: Superstore
-- Author: Paramita Kar

DESCRIBE superstore;
#Query 1: Total revenue generated by each customer
SELECT 
    customer_name,
    SUM(sales) AS total_sales
FROM superstore
GROUP BY customer_name
ORDER BY total_sales DESC;

-- Query 2: Top 10 customers by revenue
SELECT 
    customer_name,
    SUM(sales) AS total_sales
FROM superstore
GROUP BY customer_name
ORDER BY total_sales DESC
LIMIT 10;


-- Query 3: Revenue contribution by customer segment
SELECT 
    segment,
    SUM(sales) AS total_revenue
FROM superstore
GROUP BY segment
ORDER BY total_revenue DESC;


-- Query 4: Average order value per customer
SELECT 
    customer_name,
    AVG(sales) AS avg_order_value
FROM superstore
GROUP BY customer_name
ORDER BY avg_order_value DESC;

-- Query 5: Customer segmentation based on total sales

SELECT 
    customer_name,
    total_sales,
    NTILE(3) OVER (ORDER BY total_sales DESC) AS customer_segment
FROM
(
    SELECT 
        customer_name,
        SUM(sales) AS total_sales
    FROM superstore
    GROUP BY customer_name
) t;

-- Query 6: Label customer segments

SELECT 
    customer_name,
    total_sales,
    CASE 
        WHEN segment_rank = 1 THEN 'High Value'
        WHEN segment_rank = 2 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM
(
    SELECT 
        customer_name,
        SUM(sales) AS total_sales,
        NTILE(3) OVER (ORDER BY SUM(sales) DESC) AS segment_rank
    FROM superstore
    GROUP BY customer_name
) t;

-- Query 7: Revenue contribution by customer segment

SELECT 
    customer_segment,
    SUM(total_sales) AS segment_revenue,
    ROUND(
        SUM(total_sales) * 100.0 /
        SUM(SUM(total_sales)) OVER (),
        2
    ) AS revenue_percentage
FROM
(
    SELECT 
        customer_name,
        SUM(sales) AS total_sales,
        CASE 
            WHEN NTILE(3) OVER (ORDER BY SUM(sales) DESC) = 1 THEN 'High Value'
            WHEN NTILE(3) OVER (ORDER BY SUM(sales) DESC) = 2 THEN 'Medium Value'
            ELSE 'Low Value'
        END AS customer_segment
    FROM superstore
    GROUP BY customer_name
) t
GROUP BY customer_segment
ORDER BY segment_revenue DESC;